export const StorageCategories = {
  refrigerated: "Refrigerated",
  frozen: "Frozen",
  cabinet: "Cabinet",
};
export const StatusCategories = {
  expired: "Expired",
  soon: "Soon to expire",
  fresh: "Fresh",
};

export const Ingredient = [
  {
    name: "Eggs",
    storeDate: new Date(),
    expireDate: new Date(Date.now() + 2 * 86400000),
    storage: StorageCategories.refrigerated,
    status: StatusCategories.soon,
  },
  {
    name: "Eggs",
    storeDate: new Date(),
    expireDate: new Date(Date.now() + 2 * 86400000),
    storage: StorageCategories.refrigerated,
    status: StatusCategories.soon,
  },
  {
    name: "Eggs",
    storeDate: new Date(),
    expireDate: new Date(Date.now() + 2 * 86400000),
    storage: StorageCategories.refrigerated,
    status: StatusCategories.soon,
  },
  {
    name: "Eggs",
    storeDate: new Date(),
    expireDate: new Date(Date.now() + 2 * 86400000),
    storage: StorageCategories.refrigerated,
    status: StatusCategories.soon,
  },
  {
    name: "Eggs",
    storeDate: new Date(),
    expireDate: new Date(Date.now() + 2 * 86400000),
    storage: StorageCategories.refrigerated,
    status: StatusCategories.soon,
  },
  {
    name: "Eggs2",
    storeDate: new Date(),
    expireDate: new Date(Date.now() + 30 * 86400000),
    storage: StorageCategories.frozen,
    status: StatusCategories.fresh,
  },
  {
    name: "Eggs2",
    storeDate: new Date(),
    expireDate: new Date(Date.now() + 30 * 86400000),
    storage: StorageCategories.frozen,
    status: StatusCategories.fresh,
  },
  {
    name: "Eggs2",
    storeDate: new Date(),
    expireDate: new Date(Date.now() + 30 * 86400000),
    storage: StorageCategories.frozen,
    status: StatusCategories.fresh,
  },
  {
    name: "eeeeee",
    storeDate: new Date(),
    expireDate: new Date(Date.now() + 30 * 86400000),
    storage: StorageCategories.frozen,
    status: StatusCategories.fresh,
  },
  {
    name: "Eggs2",
    storeDate: new Date(),
    expireDate: new Date(Date.now() + 30 * 86400000),
    storage: StorageCategories.frozen,
    status: StatusCategories.fresh,
  },
  {
    name: "Eggs2",
    storeDate: new Date(),
    expireDate: new Date(Date.now() + 30 * 86400000),
    storage: StorageCategories.frozen,
    status: StatusCategories.fresh,
  },
  {
    name: "Eggs3",
    storeDate: new Date(),
    expireDate: new Date(),
    storage: StorageCategories.refrigerated,
    status: StatusCategories.expired,
  },
  {
    name: "Eggs3",
    storeDate: new Date(),
    expireDate: new Date(),
    storage: StorageCategories.refrigerated,
    status: StatusCategories.expired,
  },
  {
    name: "Eggs3",
    storeDate: new Date(),
    expireDate: new Date(),
    storage: StorageCategories.refrigerated,
    status: StatusCategories.expired,
  },
  {
    name: "Eggs3",
    storeDate: new Date(),
    expireDate: new Date(),
    storage: StorageCategories.refrigerated,
    status: StatusCategories.expired,
  },
];
